### ISSUE TITLE
“互联网简史”中最后一个标题有误

### ISSUE THREAD

**Issue by HermitSun** [LanceZhu/timeline#17]
如图所示：
![image](https://user-images.githubusercontent.com/35923278/83315070-2af4ef80-a250-11ea-8708-de5a1a47d7ee.png)

**Comment by LanceZhu** [comment]
已修复。也欢迎直接到互联网简史完善时间轴:wave:。:point_right: [互联网简史](http://internet.welishi.cn/#/timeline)

**Comment by HermitSun** [comment]
OK
